version: '2'
services:
  iod:
    build: .
    restart: always
    volumes:
      - ".:/usr/app"
      - "./.local/artifacts/:/processing/artifacts/"
      - "./.local/cache/:/processing/cache/"
    environment:
      ENV: Local
    command: ./manage.py exec all

  iod-test:
    build: .
    restart: always
    volumes:
      - ".:/usr/app"
      - "./commands/tests/test_data:/data"
    environment:
      ENV: Local
    command: pytest
